{% set version = "0.7" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-testit
  version: {{ version|replace("-", "_") }}

source:
  fn: testit_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/testit_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/testit/testit_{{ version }}.tar.gz


  sha256: 03332889bffe8b69d36e696e3a6a1a29713cdcbccf1efced6cddbf061fb41a1f

build:
  noarch: generic
  number: 1000

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('testit')"  # [not win]
    - "\"%R%\" -e \"library('testit')\""  # [win]



about:
  home: https://github.com/yihui/testit
  license: GPL
  summary: Provides two convenience functions assert() and test_pkg() to facilitate testing R
    packages.
  license_family: GPL



extra:
  recipe-maintainers:
    - croth1
